default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: cc-dev

test:
  <<: *default
  database: cc-testing

production:
  <<: *default
  database: cc-prod
